// Blog Data - 50 artículos categorizados
// Categorías: Seguros, Economía, Tecnología, Salud, Hogar, Vida, Ahorro, Movilidad, Legal, Actualidad

export interface BlogPost {
  id: number
  slug: string
  title: string
  excerpt: string
  content: string
  category: string
  tags: string[]
  author: string
  authorRole: string
  publishedAt: string
  readTime: string
  featured: boolean
  coverImage?: string
}

export const BLOG_CATEGORIES = [
  { name: 'Todos', slug: 'todos', color: 'neutral' },
  { name: 'Seguros', slug: 'seguros', color: 'red' },
  { name: 'Economía', slug: 'economia', color: 'emerald' },
  { name: 'Tecnología', slug: 'tecnologia', color: 'blue' },
  { name: 'Salud', slug: 'salud', color: 'violet' },
  { name: 'Hogar', slug: 'hogar', color: 'amber' },
  { name: 'Movilidad', slug: 'movilidad', color: 'orange' },
  { name: 'Ahorro', slug: 'ahorro', color: 'green' },
  { name: 'Legal', slug: 'legal', color: 'slate' },
  { name: 'Actualidad', slug: 'actualidad', color: 'cyan' },
]

export const BLOG_POSTS: BlogPost[] = [
  // ===== SEGUROS (5 artículos) =====
  {
    id: 1,
    slug: 'guia-completa-seguros-2024',
    title: 'Guía completa de seguros para 2024: Todo lo que necesitas saber',
    excerpt: 'Descubre las claves para elegir el seguro perfecto en 2024. Analizamos las tendencias, novedades legislativas y mejores prácticas para proteger tu patrimonio.',
    content: `Los seguros son una parte fundamental de la planificación financiera personal y empresarial...`,
    category: 'Seguros',
    tags: ['guía', 'seguros', '2024', 'planificación'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2024-01-15',
    readTime: '8 min',
    featured: true,
  },
  {
    id: 2,
    slug: 'diferencias-seguro-terceros-todo-riesgo',
    title: 'Terceros vs Todo Riesgo: ¿Qué seguro de coche necesitas realmente?',
    excerpt: 'Analizamos en profundidad las diferencias entre seguros a terceros y todo riesgo para ayudarte a tomar la mejor decisión según tu situación.',
    content: `Elegir entre un seguro a terceros y todo riesgo es una de las decisiones más importantes...`,
    category: 'Seguros',
    tags: ['auto', 'terceros', 'todo riesgo', 'coche'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-10',
    readTime: '6 min',
    featured: true,
  },
  {
    id: 3,
    slug: 'como-funciona-seguro-vida-hipoteca',
    title: 'Seguro de vida vinculado a la hipoteca: ¿Es obligatorio?',
    excerpt: 'Desmitificamos el seguro de vida ligado a la hipoteca. Conoce tus derechos y las alternativas disponibles para ahorrar.',
    content: `Uno de los mitos más extendidos en España es que el seguro de vida es obligatorio con la hipoteca...`,
    category: 'Seguros',
    tags: ['vida', 'hipoteca', 'obligatorio', 'ahorro'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2024-01-05',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 4,
    slug: 'siniestros-mas-comunes-hogar',
    title: 'Los 10 siniestros más comunes en el hogar y cómo prevenirlos',
    excerpt: 'Conoce los accidentes domésticos más frecuentes y aprende estrategias efectivas para evitarlos y proteger tu vivienda.',
    content: `Cada año, miles de hogares españoles sufren siniestros que podrían haberse evitado...`,
    category: 'Seguros',
    tags: ['hogar', 'siniestros', 'prevención', 'consejos'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-28',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 5,
    slug: 'seguro-salud-sin-copago-vs-con-copago',
    title: 'Seguro de salud: ¿Con copago o sin copago? Guía de decisión',
    excerpt: 'Analizamos las ventajas e inconvenientes de cada modalidad para ayudarte a elegir el seguro de salud ideal para ti y tu familia.',
    content: `El seguro de salud es una de las inversiones más importantes para tu bienestar...`,
    category: 'Seguros',
    tags: ['salud', 'copago', 'comparativa', 'familia'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-20',
    readTime: '6 min',
    featured: false,
  },

  // ===== ECONOMÍA (5 artículos) =====
  {
    id: 6,
    slug: 'inflacion-impacto-ahorro-seguros',
    title: 'Inflación en 2024: Cómo afecta a tu ahorro y seguros',
    excerpt: 'Analizamos el impacto de la inflación actual en tus finanzas personales y estrategias para proteger tu patrimonio.',
    content: `La inflación sigue siendo una de las principales preocupaciones económicas de los españoles...`,
    category: 'Economía',
    tags: ['inflación', 'ahorro', 'finanzas', '2024'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2024-01-12',
    readTime: '7 min',
    featured: true,
  },
  {
    id: 7,
    slug: 'tipos-interes-hipotecas-2024',
    title: 'Tipos de interés e hipotecas: Perspectivas para 2024',
    excerpt: 'El BCE marca el ritmo de las hipotecas. Analizamos qué esperar de los tipos de interés y cómo afectará a tu bolsillo.',
    content: `El Banco Central Europeo ha marcado un punto de inflexión en su política monetaria...`,
    category: 'Economía',
    tags: ['hipotecas', 'tipos interés', 'BCE', 'vivienda'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-08',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 8,
    slug: 'planificacion-financiera-familiar',
    title: 'Planificación financiera familiar: Los 5 pilares fundamentales',
    excerpt: 'Descubre los principios básicos para organizar las finanzas de tu familia y alcanzar tus objetivos económicos.',
    content: `La planificación financiera familiar es el proceso de gestionar los recursos económicos del hogar...`,
    category: 'Economía',
    tags: ['planificación', 'familia', 'finanzas', 'presupuesto'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-15',
    readTime: '8 min',
    featured: false,
  },
  {
    id: 9,
    slug: 'crisis-economica-proteger-patrimonio',
    title: 'Cómo proteger tu patrimonio ante una crisis económica',
    excerpt: 'Estrategias probadas para salvaguardar tus bienes y inversiones en tiempos de incertidumbre económica.',
    content: `Las crisis económicas son cíclicas y, aunque no podemos predecir exactamente cuándo ocurrirán...`,
    category: 'Economía',
    tags: ['crisis', 'patrimonio', 'inversiones', 'protección'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-12-10',
    readTime: '9 min',
    featured: false,
  },
  {
    id: 10,
    slug: 'ventajas-fiscales-seguros-ahorro',
    title: 'Ventajas fiscales de los seguros de ahorro en tu declaración',
    excerpt: 'Conoce todos los beneficios fiscales que puedes obtener con productos de ahorro y jubilación y cómo aplicarlos.',
    content: `Los productos de ahorro y jubilación ofrecen interesantes ventajas fiscales que muchos desconocen...`,
    category: 'Economía',
    tags: ['fiscalidad', 'ahorro', 'IRPF', 'declaración'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-05',
    readTime: '6 min',
    featured: false,
  },

  // ===== TECNOLOGÍA (5 artículos) =====
  {
    id: 11,
    slug: 'insurtech-revolucion-seguros',
    title: 'Insurtech: La revolución tecnológica en el sector asegurador',
    excerpt: 'Descubre cómo la tecnología está transformando la industria de los seguros y qué beneficios aporta a los clientes.',
    content: `La transformación digital ha llegado con fuerza al sector asegurador...`,
    category: 'Tecnología',
    tags: ['insurtech', 'digitalización', 'innovación', 'futuro'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2024-01-14',
    readTime: '7 min',
    featured: true,
  },
  {
    id: 12,
    slug: 'inteligencia-artificial-seguros',
    title: 'IA en seguros: Cómo la inteligencia artificial mejora tu experiencia',
    excerpt: 'La IA está revolucionando la atención al cliente, la valoración de riesgos y la gestión de siniestros en el sector asegurador.',
    content: `La inteligencia artificial está redefiniendo la forma en que las aseguradoras operan...`,
    category: 'Tecnología',
    tags: ['IA', 'chatbots', 'automatización', 'innovación'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2024-01-09',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 13,
    slug: 'ciberseguridad-proteger-datos',
    title: 'Ciberseguridad: Cómo proteger tus datos personales online',
    excerpt: 'Consejos prácticos para mantener tu información personal segura en internet y evitar fraudes digitales.',
    content: `En la era digital, la protección de nuestros datos personales es más importante que nunca...`,
    category: 'Tecnología',
    tags: ['ciberseguridad', 'privacidad', 'datos', 'fraudes'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2023-12-22',
    readTime: '8 min',
    featured: false,
  },
  {
    id: 14,
    slug: 'telemedicina-futuro-salud',
    title: 'Telemedicina: El futuro de la atención sanitaria ya está aquí',
    excerpt: 'La videoconsulta médica se ha consolidado como una alternativa eficaz. Conoce sus ventajas y cómo aprovecharla.',
    content: `La pandemia aceleró la adopción de la telemedicina de forma exponencial...`,
    category: 'Tecnología',
    tags: ['telemedicina', 'videoconsulta', 'salud digital', 'innovación'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-18',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 15,
    slug: 'app-movil-gestion-seguros',
    title: 'Apps móviles para gestionar tus seguros: Guía completa',
    excerpt: 'Descubre las funcionalidades que ofrecen las aplicaciones móviles de las aseguradoras y cómo sacarles el máximo partido.',
    content: `Las aplicaciones móviles han transformado la forma en que gestionamos nuestros seguros...`,
    category: 'Tecnología',
    tags: ['apps', 'móvil', 'gestión', 'digital'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2023-12-12',
    readTime: '6 min',
    featured: false,
  },

  // ===== SALUD (5 artículos) =====
  {
    id: 16,
    slug: 'prevencion-enfermedades-cardiovasculares',
    title: 'Prevención de enfermedades cardiovasculares: Guía práctica',
    excerpt: 'Las enfermedades del corazón son la primera causa de muerte. Aprende a prevenirlas con hábitos saludables.',
    content: `Las enfermedades cardiovasculares representan la principal causa de mortalidad en España...`,
    category: 'Salud',
    tags: ['corazón', 'prevención', 'hábitos', 'salud'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2024-01-11',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 17,
    slug: 'salud-mental-importancia-cuidarla',
    title: 'Salud mental: Por qué es tan importante cuidarla',
    excerpt: 'La salud mental es fundamental para nuestro bienestar. Conoce los recursos disponibles y cómo los seguros pueden ayudarte.',
    content: `La salud mental ha dejado de ser un tabú para convertirse en una prioridad social...`,
    category: 'Salud',
    tags: ['salud mental', 'bienestar', 'psicología', 'cobertura'],
    author: 'Tania Zhyla',
    authorRole: 'Asesora Comercial',
    publishedAt: '2024-01-06',
    readTime: '6 min',
    featured: true,
  },
  {
    id: 18,
    slug: 'nutricion-alimentacion-saludable',
    title: 'Nutrición y alimentación saludable: Claves para tu bienestar',
    excerpt: 'Una buena alimentación es la base de una vida sana. Descubre las claves de una dieta equilibrada.',
    content: `La nutrición es uno de los pilares fundamentales de la salud...`,
    category: 'Salud',
    tags: ['nutrición', 'dieta', 'alimentación', 'bienestar'],
    author: 'Alberto Alcalá',
    authorRole: 'Agente Atención Cliente',
    publishedAt: '2023-12-25',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 19,
    slug: 'chequeos-medicos-preventivos',
    title: 'Chequeos médicos preventivos: ¿Cuáles necesitas según tu edad?',
    excerpt: 'La prevención es la mejor medicina. Conoce qué pruebas médicas deberías realizarte según tu etapa de vida.',
    content: `Los chequeos médicos preventivos son fundamentales para detectar enfermedades a tiempo...`,
    category: 'Salud',
    tags: ['chequeos', 'prevención', 'medicina', 'edad'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-19',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 20,
    slug: 'ejercicio-fisico-beneficios',
    title: 'Ejercicio físico: Beneficios para cuerpo y mente',
    excerpt: 'El deporte es medicina. Descubre todos los beneficios del ejercicio regular y cómo empezar.',
    content: `El ejercicio físico regular es una de las mejores inversiones que puedes hacer en tu salud...`,
    category: 'Salud',
    tags: ['ejercicio', 'deporte', 'fitness', 'bienestar'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-14',
    readTime: '6 min',
    featured: false,
  },

  // ===== HOGAR (5 artículos) =====
  {
    id: 21,
    slug: 'eficiencia-energetica-hogar',
    title: 'Eficiencia energética en el hogar: Ahorra en tus facturas',
    excerpt: 'Consejos prácticos para reducir el consumo energético de tu vivienda y ahorrar en luz y gas.',
    content: `La eficiencia energética no solo es buena para el medio ambiente, también para tu bolsillo...`,
    category: 'Hogar',
    tags: ['energía', 'ahorro', 'facturas', 'sostenibilidad'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-13',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 22,
    slug: 'seguridad-hogar-sistemas-alarma',
    title: 'Sistemas de seguridad para el hogar: Guía de compra',
    excerpt: 'Protege tu vivienda con los sistemas de seguridad más eficaces. Comparamos opciones y precios.',
    content: `La seguridad del hogar es una prioridad para cualquier familia...`,
    category: 'Hogar',
    tags: ['seguridad', 'alarmas', 'protección', 'tecnología'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2024-01-07',
    readTime: '8 min',
    featured: true,
  },
  {
    id: 23,
    slug: 'mantenimiento-hogar-estacional',
    title: 'Mantenimiento del hogar: Tareas estacionales imprescindibles',
    excerpt: 'Un buen mantenimiento previene siniestros. Conoce las tareas que debes realizar en cada estación.',
    content: `El mantenimiento preventivo del hogar es fundamental para evitar problemas mayores...`,
    category: 'Hogar',
    tags: ['mantenimiento', 'prevención', 'estaciones', 'consejos'],
    author: 'Alberto Alcalá',
    authorRole: 'Agente Atención Cliente',
    publishedAt: '2023-12-23',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 24,
    slug: 'reformas-hogar-valorar-vivienda',
    title: 'Reformas que valorizan tu vivienda: ¿Cuáles merece la pena?',
    excerpt: 'No todas las reformas aportan el mismo valor. Descubre cuáles son las más rentables para tu inversión.',
    content: `Reformar una vivienda es una inversión importante que debe planificarse bien...`,
    category: 'Hogar',
    tags: ['reformas', 'inversión', 'vivienda', 'valor'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-12-17',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 25,
    slug: 'comunidad-propietarios-derechos',
    title: 'Comunidad de propietarios: Tus derechos y obligaciones',
    excerpt: 'Vivir en comunidad implica derechos pero también responsabilidades. Conoce la normativa básica.',
    content: `La vida en comunidad de propietarios está regulada por la Ley de Propiedad Horizontal...`,
    category: 'Hogar',
    tags: ['comunidad', 'propietarios', 'derechos', 'normativa'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-11',
    readTime: '8 min',
    featured: false,
  },

  // ===== MOVILIDAD (5 artículos) =====
  {
    id: 26,
    slug: 'coches-electricos-guia-compra',
    title: 'Coches eléctricos: Guía definitiva para el comprador',
    excerpt: 'Todo lo que necesitas saber antes de dar el salto al vehículo eléctrico: autonomía, carga, ayudas y seguros.',
    content: `Los coches eléctricos han dejado de ser el futuro para convertirse en el presente...`,
    category: 'Movilidad',
    tags: ['eléctricos', 'coches', 'movilidad', 'sostenibilidad'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-10',
    readTime: '9 min',
    featured: true,
  },
  {
    id: 27,
    slug: 'conduccion-segura-invierno',
    title: 'Conducción segura en invierno: Consejos imprescindibles',
    excerpt: 'El frío, la lluvia y la nieve requieren precauciones especiales. Aprende a conducir con seguridad.',
    content: `El invierno presenta desafíos únicos para los conductores...`,
    category: 'Movilidad',
    tags: ['conducción', 'invierno', 'seguridad', 'consejos'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2024-01-04',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 28,
    slug: 'patinetes-electricos-normativa',
    title: 'Patinetes eléctricos: Normativa y seguros en 2024',
    excerpt: 'Los VMP tienen sus propias reglas. Conoce la normativa actual y las coberturas de seguro disponibles.',
    content: `Los patinetes eléctricos se han convertido en un medio de transporte urbano muy popular...`,
    category: 'Movilidad',
    tags: ['patinetes', 'VMP', 'normativa', 'seguro'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-27',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 29,
    slug: 'mantenimiento-coche-basico',
    title: 'Mantenimiento básico del coche: Lo que debes revisar',
    excerpt: 'Un buen mantenimiento alarga la vida de tu vehículo y previene averías. Conoce las revisiones básicas.',
    content: `El mantenimiento preventivo de tu coche es fundamental para su buen funcionamiento...`,
    category: 'Movilidad',
    tags: ['mantenimiento', 'coche', 'revisiones', 'mecánica'],
    author: 'Alberto Alcalá',
    authorRole: 'Agente Atención Cliente',
    publishedAt: '2023-12-21',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 30,
    slug: 'flotas-vehiculos-empresas',
    title: 'Gestión de flotas: Optimiza los vehículos de tu empresa',
    excerpt: 'Consejos para gestionar eficientemente la flota de vehículos de tu empresa y reducir costes.',
    content: `La gestión de flotas es un aspecto crucial para muchas empresas...`,
    category: 'Movilidad',
    tags: ['flotas', 'empresas', 'gestión', 'optimización'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-12-16',
    readTime: '8 min',
    featured: false,
  },

  // ===== AHORRO (5 artículos) =====
  {
    id: 31,
    slug: 'jubilacion-cuando-empezar-ahorrar',
    title: 'Jubilación: ¿Cuándo es el mejor momento para empezar a ahorrar?',
    excerpt: 'El tiempo es tu mejor aliado para la jubilación. Descubre por qué nunca es demasiado pronto para empezar.',
    content: `Planificar la jubilación es una de las decisiones financieras más importantes...`,
    category: 'Ahorro',
    tags: ['jubilación', 'ahorro', 'pensiones', 'planificación'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2024-01-08',
    readTime: '7 min',
    featured: true,
  },
  {
    id: 32,
    slug: 'planes-pensiones-vs-pias',
    title: 'Planes de pensiones vs PIAS: ¿Cuál te conviene más?',
    excerpt: 'Comparamos los dos productos estrella para el ahorro a largo plazo y te ayudamos a elegir.',
    content: `Elegir entre un plan de pensiones y un PIAS depende de tu situación personal...`,
    category: 'Ahorro',
    tags: ['planes pensiones', 'PIAS', 'comparativa', 'inversión'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-03',
    readTime: '8 min',
    featured: false,
  },
  {
    id: 33,
    slug: 'fondo-emergencia-como-crearlo',
    title: 'Fondo de emergencia: Cómo crearlo y cuánto necesitas',
    excerpt: 'El colchón financiero que todos necesitamos. Aprende a calcular y construir tu fondo de emergencia.',
    content: `Un fondo de emergencia es la primera línea de defensa financiera...`,
    category: 'Ahorro',
    tags: ['emergencia', 'fondo', 'ahorro', 'finanzas'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-26',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 34,
    slug: 'inversiones-bajo-riesgo',
    title: 'Inversiones de bajo riesgo: Opciones para perfiles conservadores',
    excerpt: 'No todo el mundo quiere arriesgar su dinero. Conoce las opciones más seguras para hacer crecer tu ahorro.',
    content: `Invertir no tiene por qué significar asumir grandes riesgos...`,
    category: 'Ahorro',
    tags: ['inversiones', 'bajo riesgo', 'conservador', 'seguridad'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-20',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 35,
    slug: 'educacion-financiera-hijos',
    title: 'Educación financiera para hijos: Enseña a ahorrar desde pequeños',
    excerpt: 'Los buenos hábitos financieros se aprenden desde la infancia. Estrategias para educar a tus hijos.',
    content: `La educación financiera debería comenzar en casa desde temprana edad...`,
    category: 'Ahorro',
    tags: ['educación', 'hijos', 'finanzas', 'familia'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-13',
    readTime: '6 min',
    featured: false,
  },

  // ===== LEGAL (5 artículos) =====
  {
    id: 36,
    slug: 'nueva-ley-seguros-2024',
    title: 'Nueva normativa de seguros 2024: Lo que debes saber',
    excerpt: 'Analizamos los cambios legislativos que afectan al sector asegurador y cómo te impactan como cliente.',
    content: `El marco regulatorio de los seguros está en constante evolución...`,
    category: 'Legal',
    tags: ['legislación', 'normativa', '2024', 'seguros'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2024-01-09',
    readTime: '8 min',
    featured: false,
  },
  {
    id: 37,
    slug: 'reclamaciones-seguros-como-hacerlo',
    title: 'Cómo reclamar a tu aseguradora: Guía paso a paso',
    excerpt: 'Si no estás satisfecho con la respuesta de tu aseguradora, tienes opciones. Te explicamos el proceso.',
    content: `Las reclamaciones son un derecho del asegurado que conviene conocer...`,
    category: 'Legal',
    tags: ['reclamaciones', 'derechos', 'asegurado', 'proceso'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2024-01-02',
    readTime: '7 min',
    featured: true,
  },
  {
    id: 38,
    slug: 'testamento-herencias-planificacion',
    title: 'Testamento y herencias: Planifica el futuro de tu familia',
    excerpt: 'El testamento es una herramienta esencial para proteger a los tuyos. Conoce cómo hacerlo correctamente.',
    content: `Hacer testamento es un acto de responsabilidad hacia nuestros seres queridos...`,
    category: 'Legal',
    tags: ['testamento', 'herencias', 'sucesiones', 'familia'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-24',
    readTime: '9 min',
    featured: false,
  },
  {
    id: 39,
    slug: 'proteccion-datos-seguros',
    title: 'Protección de datos en seguros: Tus derechos RGPD',
    excerpt: 'Las aseguradoras manejan mucha información personal. Conoce tus derechos según el RGPD.',
    content: `El Reglamento General de Protección de Datos afecta directamente al sector asegurador...`,
    category: 'Legal',
    tags: ['RGPD', 'privacidad', 'datos', 'derechos'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2023-12-18',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 40,
    slug: 'mediador-seguros-ventajas',
    title: 'Contratar seguros con mediador: Ventajas legales',
    excerpt: 'Los mediadores de seguros ofrecen ventajas legales que las aseguradoras directas no pueden. Descúbrelas.',
    content: `Los mediadores de seguros estamos regulados por la DGSFP y ofrecemos garantías adicionales...`,
    category: 'Legal',
    tags: ['mediador', 'corredor', 'ventajas', 'DGSFP'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-12-09',
    readTime: '5 min',
    featured: false,
  },

  // ===== ACTUALIDAD (10 artículos) =====
  {
    id: 41,
    slug: 'dana-inundaciones-como-actuar',
    title: 'DANA e inundaciones: Cómo actuar y qué cubre tu seguro',
    excerpt: 'Los fenómenos meteorológicos extremos son cada vez más frecuentes. Conoce cómo protegerte.',
    content: `Las DANAs y otros fenómenos meteorológicos extremos son cada vez más habituales en España...`,
    category: 'Actualidad',
    tags: ['DANA', 'inundaciones', 'climatología', 'siniestros'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2024-01-14',
    readTime: '6 min',
    featured: true,
  },
  {
    id: 42,
    slug: 'turismo-seniors-seguros-viaje',
    title: 'Turismo senior: Seguros de viaje para mayores de 65',
    excerpt: 'Viajar no tiene edad. Conoce las coberturas específicas para viajeros senior y viaja con tranquilidad.',
    content: `El turismo senior es un segmento en crecimiento que requiere coberturas específicas...`,
    category: 'Actualidad',
    tags: ['seniors', 'viajes', 'turismo', 'seguros'],
    author: 'Tania Zhyla',
    authorRole: 'Asesora Comercial',
    publishedAt: '2024-01-07',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 43,
    slug: 'teletrabajo-seguros-hogar-modificar',
    title: 'Teletrabajo: ¿Necesitas modificar tu seguro de hogar?',
    excerpt: 'Trabajar desde casa puede requerir ajustes en tu póliza. Analizamos las coberturas necesarias.',
    content: `El teletrabajo ha cambiado nuestra relación con el hogar y también con los seguros...`,
    category: 'Actualidad',
    tags: ['teletrabajo', 'hogar', 'oficina', 'coberturas'],
    author: 'Alberto Alcalá',
    authorRole: 'Agente Atención Cliente',
    publishedAt: '2023-12-29',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 44,
    slug: 'mascotas-seguros-responsabilidad',
    title: 'Seguros para mascotas: Responsabilidad civil y salud',
    excerpt: 'Nuestros animales de compañía merecen protección. Conoce los seguros disponibles y sus coberturas.',
    content: `Las mascotas son parte de la familia y como tales merecen protección...`,
    category: 'Actualidad',
    tags: ['mascotas', 'perros', 'RC', 'veterinario'],
    author: 'Toni Medina',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-22',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 45,
    slug: 'black-friday-seguros-ofertas',
    title: 'Black Friday en seguros: ¿Merece la pena?',
    excerpt: 'Analizamos si las ofertas de seguros en Black Friday son realmente ventajosas o solo marketing.',
    content: `El Black Friday ha llegado también al sector asegurador, pero ¿son reales las ofertas?...`,
    category: 'Actualidad',
    tags: ['Black Friday', 'ofertas', 'descuentos', 'análisis'],
    author: 'Pau Ripoll',
    authorRole: 'Subdirector',
    publishedAt: '2023-11-20',
    readTime: '4 min',
    featured: false,
  },
  {
    id: 46,
    slug: 'navidad-segura-consejos-hogar',
    title: 'Navidad segura: Consejos para proteger tu hogar',
    excerpt: 'Las fiestas navideñas traen riesgos específicos para el hogar. Consejos para unas fiestas sin sobresaltos.',
    content: `La Navidad es época de celebración pero también de precaución extra en el hogar...`,
    category: 'Actualidad',
    tags: ['Navidad', 'hogar', 'seguridad', 'fiestas'],
    author: 'Laura Fernández',
    authorRole: 'Resp. Atención Cliente',
    publishedAt: '2023-12-15',
    readTime: '5 min',
    featured: false,
  },
  {
    id: 47,
    slug: 'cambio-climatico-seguros-futuro',
    title: 'Cambio climático: El impacto en los seguros del futuro',
    excerpt: 'El calentamiento global está redefiniendo el sector asegurador. Analizamos las tendencias.',
    content: `El cambio climático es uno de los mayores desafíos para el sector asegurador...`,
    category: 'Actualidad',
    tags: ['clima', 'sostenibilidad', 'futuro', 'riesgos'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-12-08',
    readTime: '8 min',
    featured: false,
  },
  {
    id: 48,
    slug: 'autonomos-obligaciones-seguros',
    title: 'Autónomos: Seguros obligatorios y recomendados en 2024',
    excerpt: 'Si eres autónomo, conocer tus obligaciones en materia de seguros es fundamental. Te lo explicamos.',
    content: `Los trabajadores autónomos tienen obligaciones específicas en materia de seguros...`,
    category: 'Actualidad',
    tags: ['autónomos', 'obligatorios', 'RC', 'profesional'],
    author: 'Juan Ignacio Pérez',
    authorRole: 'Asesor Comercial',
    publishedAt: '2023-12-01',
    readTime: '7 min',
    featured: false,
  },
  {
    id: 49,
    slug: 'generacion-z-seguros-digitales',
    title: 'Generación Z: ¿Cómo contratan seguros los jóvenes?',
    excerpt: 'Los jóvenes tienen nuevas expectativas sobre los seguros. Analizamos sus preferencias digitales.',
    content: `La Generación Z está transformando la forma de contratar seguros...`,
    category: 'Actualidad',
    tags: ['jóvenes', 'digital', 'tendencias', 'generación Z'],
    author: 'Héctor Nolivos',
    authorRole: 'Responsable TIC',
    publishedAt: '2023-11-25',
    readTime: '6 min',
    featured: false,
  },
  {
    id: 50,
    slug: 'villajoyosa-comunidad-seguros',
    title: 'Villajoyosa y la Marina Baixa: Tu correduría de seguros local',
    excerpt: 'Descubre las ventajas de contratar tus seguros con un mediador local que conoce tu comunidad.',
    content: `En Soriano Mediadores llevamos más de 25 años sirviendo a la comunidad de Villajoyosa y la Marina Baixa...`,
    category: 'Actualidad',
    tags: ['Villajoyosa', 'local', 'comunidad', 'cercanía'],
    author: 'Ramón Soriano',
    authorRole: 'Director',
    publishedAt: '2023-11-15',
    readTime: '5 min',
    featured: true,
  },
]

// Helper functions
export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(post => post.slug === slug)
}

export function getBlogPostsByCategory(category: string): BlogPost[] {
  if (category === 'todos') return BLOG_POSTS
  return BLOG_POSTS.filter(post => post.category.toLowerCase() === category.toLowerCase())
}

export function getFeaturedPosts(): BlogPost[] {
  return BLOG_POSTS.filter(post => post.featured)
}

export function getRecentPosts(limit: number = 6): BlogPost[] {
  return [...BLOG_POSTS]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit)
}

export function getRelatedPosts(currentSlug: string, limit: number = 3): BlogPost[] {
  const currentPost = getBlogPostBySlug(currentSlug)
  if (!currentPost) return []

  return BLOG_POSTS
    .filter(post => post.slug !== currentSlug && post.category === currentPost.category)
    .slice(0, limit)
}
