export const COMPANY_INFO = {
  name: 'Soriano Mediadores',
  fullName: 'Soriano Mediadores de Seguros S.L.',
  tagline: 'Tu tranquilidad, nuestra prioridad',
  description: 'Mediadores de seguros de confianza desde hace más de 25 años',
  phone: '+34 966 810 290',
  phoneClean: '+34966810290',
  email: 'info@sorianomediadores.es',
  address: {
    street: 'Calle Constitución 5',
    city: 'Villajoyosa',
    province: 'Alicante',
    postalCode: '03570',
    country: 'España',
    full: 'Calle Constitución 5, 03570 Villajoyosa, Alicante',
    coordinates: {
      lat: 38.5076,
      lng: -0.2329,
    },
  },
  schedule: {
    weekdays: '09:00 - 17:00',
    saturday: '10:00 - 14:00',
    sunday: 'Cerrado',
  },
  social: {
    facebook: 'https://facebook.com/sorianomediadores',
    instagram: 'https://instagram.com/sorianomediadores',
    linkedin: 'https://linkedin.com/company/sorianomediadores',
    twitter: 'https://twitter.com/sorianomediadores',
  },
  legal: {
    nif: 'B12345678',
    registroMercantil: 'Alicante, Tomo 1234, Folio 56, Hoja A-12345',
    dgsfp: 'C0123A12345678',
  },
}

export const OCCIDENT_INFO = {
  name: 'Occident',
  fullName: 'Grupo Catalana Occidente',
  satisfaction: 8.4,
  averageRelationYears: 10.8,
  offices: 1200,
  clients: 4000000,
  professionals: 2900,
  medicalServices: 44000,
}

export const INSURANCE_PRODUCTS = {
  auto: {
    name: 'Seguros de Coche',
    slug: 'seguro-coche',
    icon: 'Car',
    description: 'Protege tu vehículo con las mejores coberturas',
    types: [
      { name: 'Terceros Básico', price: 'desde 180€/año' },
      { name: 'Terceros Completo', price: 'desde 250€/año' },
      { name: 'Todo Riesgo con Franquicia', price: 'desde 380€/año' },
      { name: 'Todo Riesgo sin Franquicia', price: 'desde 520€/año' },
    ],
    features: [
      'Asistencia en carretera 24/7',
      'Vehículo de sustitución',
      'Red de talleres AutoPresto',
      'Defensa jurídica incluida',
      'Tramitación de multas',
    ],
  },
  moto: {
    name: 'Seguros de Moto',
    slug: 'seguro-moto',
    icon: 'Bike',
    description: 'Libertad sobre dos ruedas, con total protección',
    types: [
      { name: 'Terceros', price: 'desde 120€/año' },
      { name: 'Terceros Completo', price: 'desde 180€/año' },
      { name: 'Todo Riesgo', price: 'desde 280€/año' },
    ],
    features: [
      'Cobertura de equipamiento',
      'Asistencia en carretera',
      'Responsabilidad civil',
      'Defensa jurídica',
    ],
  },
  hogar: {
    name: 'Seguros de Hogar',
    slug: 'seguro-hogar',
    icon: 'Home',
    description: 'Tu hogar, tu refugio. Protégelo como se merece',
    types: [
      { name: 'Hogar Básico', price: 'desde 150€/año' },
      { name: 'Hogar Completo', price: 'desde 220€/año' },
      { name: 'Hogar Exclusivo', price: 'desde 350€/año' },
      { name: 'Hogar Arrendador', price: 'desde 180€/año' },
    ],
    features: [
      'Incendio y daños por agua',
      'Robo y vandalismo',
      'Responsabilidad civil',
      'Asistencia hogar 24h',
      'Bricohogar incluido',
    ],
  },
  vida: {
    name: 'Seguros de Vida',
    slug: 'seguro-vida',
    icon: 'Heart',
    description: 'Protege el futuro de los tuyos',
    types: [
      { name: 'Vida Temporal', price: 'desde 8€/mes' },
      { name: 'Vida Amortización', price: 'desde 12€/mes' },
      { name: 'Accidentes', price: 'desde 6€/mes' },
    ],
    features: [
      'Capital asegurado flexible',
      'Cobertura de invalidez',
      'Enfermedades graves',
      'Sin reconocimiento médico hasta 50.000€',
    ],
  },
  salud: {
    name: 'Seguros de Salud',
    slug: 'seguro-salud',
    icon: 'Stethoscope',
    description: 'Tu salud es lo primero. Cuídate con las mejores coberturas',
    types: [
      { name: 'Salud con Copago', price: 'desde 35€/mes' },
      { name: 'Salud Reembolso', price: 'desde 85€/mes' },
      { name: 'Bienestar Sénior', price: 'desde 45€/mes' },
    ],
    features: [
      '44.000 servicios médicos',
      'Videoconsulta 24h',
      'Segunda opinión médica',
      'Sin carencias en muchas coberturas',
      'Cuadro médico completo',
    ],
  },
  ahorro: {
    name: 'Ahorro y Jubilación',
    slug: 'ahorro-jubilacion',
    icon: 'PiggyBank',
    description: 'Planifica tu futuro financiero con tranquilidad',
    types: [
      { name: 'Plan de Pensiones', price: 'aportaciones desde 50€/mes' },
      { name: 'PIAS', price: 'desde 100€/mes' },
      { name: 'Vida Ahorro', price: 'desde 150€/mes' },
    ],
    features: [
      'Ventajas fiscales',
      'Flexibilidad de aportaciones',
      'Diferentes perfiles de riesgo',
      'Asesoramiento personalizado',
    ],
  },
  decesos: {
    name: 'Seguros de Decesos',
    slug: 'seguro-decesos',
    icon: 'Shield',
    description: 'Tranquilidad para ti y los tuyos en los momentos difíciles',
    types: [
      { name: 'Decesos Familiar', price: 'desde 6€/mes' },
      { name: 'Decesos Sénior', price: 'desde 15€/mes' },
      { name: 'Repatriación', price: 'desde 4€/mes' },
    ],
    features: [
      'Cobertura mundial',
      'Gestión completa',
      'Asistencia familiar',
      'Testamento online',
      'Borrado digital',
    ],
  },
  comunidades: {
    name: 'Comunidades',
    slug: 'seguro-comunidades',
    icon: 'Building',
    description: 'Protección integral para tu comunidad de vecinos',
    types: [
      { name: 'Comunidades Básico', price: 'consultar' },
      { name: 'Comunidades Completo', price: 'consultar' },
    ],
    features: [
      'Daños al edificio',
      'Responsabilidad civil',
      'Defensa jurídica',
      'Asistencia 24h',
    ],
  },
}

export const STATS = [
  { value: '25+', label: 'Años de experiencia', suffix: '' },
  { value: '4M', label: 'Clientes Occident', suffix: '+' },
  { value: '8.4', label: 'Satisfacción media', suffix: '/10' },
  { value: '1200', label: 'Oficinas a tu servicio', suffix: '' },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'María García',
    role: 'Cliente desde 2018',
    avatar: '/testimonials/maria.jpg',
    content: 'El trato personalizado de Soriano Mediadores es excepcional. Me ayudaron a encontrar el seguro perfecto para mi familia y siempre están disponibles cuando los necesito.',
    rating: 5,
    product: 'Seguro de Hogar',
  },
  {
    id: 2,
    name: 'Carlos Martínez',
    role: 'Cliente desde 2015',
    avatar: '/testimonials/carlos.jpg',
    content: 'Después de un accidente, la gestión del siniestro fue impecable. En menos de una semana tenía mi coche reparado y un vehículo de sustitución mientras tanto.',
    rating: 5,
    product: 'Seguro de Coche',
  },
  {
    id: 3,
    name: 'Ana Rodríguez',
    role: 'Cliente desde 2020',
    avatar: '/testimonials/ana.jpg',
    content: 'Gracias a su asesoramiento, ahora tengo un plan de pensiones que se adapta perfectamente a mis necesidades. La transparencia y profesionalidad son su marca.',
    rating: 5,
    product: 'Plan de Pensiones',
  },
  {
    id: 4,
    name: 'Pedro Sánchez',
    role: 'Cliente desde 2019',
    avatar: '/testimonials/pedro.jpg',
    content: 'El seguro de salud de Occident que me recomendaron ha sido una de las mejores decisiones. La videoconsulta 24h me ha salvado en más de una ocasión.',
    rating: 5,
    product: 'Seguro de Salud',
  },
]

export const FAQS = [
  {
    question: '¿Qué ventajas tiene contratar a través de un mediador?',
    answer: 'Como mediadores independientes, trabajamos para ti, no para la aseguradora. Te ofrecemos asesoramiento personalizado, comparamos diferentes opciones, gestionamos tus siniestros y te acompañamos durante toda la vida de tu póliza sin coste adicional.',
  },
  {
    question: '¿Cuánto tiempo tarda en activarse mi seguro?',
    answer: 'La mayoría de seguros se activan en 24-48 horas desde la firma del contrato. En casos urgentes, podemos gestionar activaciones el mismo día.',
  },
  {
    question: '¿Qué hago si tengo un siniestro?',
    answer: 'Contacta con nosotros inmediatamente al 966 810 290 o a través del área de clientes. Nos encargamos de toda la gestión: apertura del parte, coordinación con peritos, seguimiento y resolución.',
  },
  {
    question: '¿Puedo modificar mi póliza en cualquier momento?',
    answer: 'Sí, puedes ajustar coberturas, cambiar datos o añadir asegurados en cualquier momento. Contacta con nosotros y gestionamos los cambios sin complicaciones.',
  },
  {
    question: '¿Qué documentación necesito para contratar?',
    answer: 'Generalmente necesitamos DNI/NIE, datos de contacto y, dependiendo del tipo de seguro, información específica (matrícula del vehículo, dirección del inmueble, etc.).',
  },
  {
    question: '¿Ofrecéis seguros para empresas y autónomos?',
    answer: 'Sí, tenemos soluciones específicas para empresas de todos los tamaños y autónomos: RC profesional, seguros de comercio, flotas de vehículos, convenios de salud y más.',
  },
]

export const NAV_LINKS = [
  { name: 'Inicio', href: '/' },
  {
    name: 'Seguros',
    href: '/seguros',
    children: [
      { name: 'Coche', href: '/seguros/coche', icon: 'Car' },
      { name: 'Moto', href: '/seguros/moto', icon: 'Bike' },
      { name: 'Hogar', href: '/seguros/hogar', icon: 'Home' },
      { name: 'Vida', href: '/seguros/vida', icon: 'Heart' },
      { name: 'Salud', href: '/seguros/salud', icon: 'Stethoscope' },
      { name: 'Ahorro', href: '/seguros/ahorro', icon: 'PiggyBank' },
      { name: 'Decesos', href: '/seguros/decesos', icon: 'Shield' },
      { name: 'Comunidades', href: '/seguros/comunidades', icon: 'Building' },
    ],
  },
  { name: 'Particulares', href: '/particulares' },
  { name: 'Autónomos', href: '/autonomos' },
  { name: 'Empresas', href: '/empresas' },
  { name: 'Quiénes Somos', href: '/quienes-somos' },
  { name: 'Soriano Club', href: '/comunidad' },
  { name: 'Contacto', href: '/contacto' },
]

// Testimonios categorizados por tipo de cliente
export const TESTIMONIALS_CATEGORIZED = {
  particulares: [
    {
      id: 1,
      name: 'María García Fernández',
      role: 'Cliente desde 2018',
      type: 'particular',
      product: 'Seguro de Hogar',
      content: 'Tras una inundación en casa, Soriano Mediadores gestionó todo de forma impecable. En menos de una semana teníamos los peritos, y la reparación se hizo sin ningún problema. El trato humano marca la diferencia.',
      rating: 5,
      verified: true,
      location: 'Villajoyosa',
    },
    {
      id: 2,
      name: 'Carlos Martínez López',
      role: 'Cliente desde 2015',
      type: 'particular',
      product: 'Seguro de Coche',
      content: 'Después de un accidente, la gestión del siniestro fue impecable. En menos de una semana tenía mi coche reparado y un vehículo de sustitución mientras tanto. Profesionalidad máxima.',
      rating: 5,
      verified: true,
      location: 'Benidorm',
    },
    {
      id: 3,
      name: 'Ana Rodríguez Pérez',
      role: 'Cliente desde 2020',
      type: 'particular',
      product: 'Seguro de Vida',
      content: 'Gracias a su asesoramiento, ahora tengo un seguro de vida que protege a mi familia. Me explicaron todas las opciones con claridad y sin presiones. Totalmente recomendables.',
      rating: 5,
      verified: true,
      location: 'Altea',
    },
  ],
  autonomos: [
    {
      id: 4,
      name: 'Pedro Sánchez Ruiz',
      role: 'Fontanero autónomo',
      type: 'autonomo',
      profession: 'Fontanería',
      product: 'RC Profesional',
      content: 'Como autónomo necesitaba un seguro de responsabilidad civil que me cubriera bien. En Soriano me encontraron la mejor opción calidad-precio y siempre están disponibles para cualquier duda.',
      rating: 5,
      verified: true,
      location: 'La Vila Joiosa',
    },
    {
      id: 5,
      name: 'Elena Ruiz Gómez',
      role: 'Abogada',
      type: 'autonomo',
      profession: 'Servicios Jurídicos',
      product: 'RC Profesional + Salud',
      content: 'Llevo 5 años con ellos y no podría estar más satisfecha. Mi RC profesional está perfectamente adaptada a mis necesidades como abogada, y el seguro de salud es fantástico.',
      rating: 5,
      verified: true,
      location: 'Benidorm',
    },
    {
      id: 6,
      name: 'Miguel Torres Vidal',
      role: 'Arquitecto técnico',
      type: 'autonomo',
      profession: 'Arquitectura',
      product: 'Multirriesgo Profesional',
      content: 'El seguro decenal y la RC que me gestionaron son exactamente lo que necesitaba. Además, cuando tuve una reclamación, lo resolvieron en tiempo récord.',
      rating: 5,
      verified: true,
      location: 'Alfaz del Pi',
    },
  ],
  empresas: [
    {
      id: 7,
      name: 'Construcciones Vila S.A.',
      role: 'Empresa constructora',
      type: 'empresa',
      sector: 'Construcción',
      product: 'Flota + RC Empresarial',
      content: 'Gestionan toda nuestra flota de 15 vehiculos y la responsabilidad civil de la empresa. El ahorro respecto a lo que pagabamos antes es considerable, y el servicio es mucho mejor.',
      rating: 5,
      verified: true,
      contact: 'Antonio Vila, Director',
    },
    {
      id: 8,
      name: 'Hotel Marina Bay',
      role: 'Hotel 4 estrellas',
      type: 'empresa',
      sector: 'Hostelería',
      product: 'Multirriesgo Hotelero',
      content: 'Un hotel requiere coberturas muy específicas. Soriano Mediadores entendió perfectamente nuestras necesidades y nos ofreció un seguro a medida que nos da total tranquilidad.',
      rating: 5,
      verified: true,
      contact: 'Laura Mendez, Gerente',
    },
    {
      id: 9,
      name: 'Clínica Dental Sonrisa',
      role: 'Clínica dental',
      type: 'empresa',
      sector: 'Salud',
      product: 'RC Sanitaria + Multirriesgo',
      content: 'La RC sanitaria es fundamental en nuestro sector. Nos asesoran perfectamente y siempre están al día de la normativa. Además, el convenio de salud para empleados es excelente.',
      rating: 5,
      verified: true,
      contact: 'Dr. Javier Ortiz',
    },
  ],
}
